test: test_async_dns_resolver_unix.ml
	corebuild -pkg async,core,dns,cstruct,cstruct.syntax,re,re.str,ipaddr,io-page.unix,base64 test_async_dns_resolver_unix.native

clean:
	rm -rf _build *.native

.PHONY: infer, clean
